CI: Allow danger to fail on forks
Allow the `danger` job to fail, explicitly on `FORK_MR_PIPELINE`

Signed-off-by: Raimund Hook <rhook@gitlab.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -509,7 +509,14 @@ danger-review:
   script:
     - git version
     - danger_id=$(echo -n ${DANGER_GITLAB_API_TOKEN} | md5sum | awk '{print $1}' | cut -c5-10)
+    - |
+      if [ -v DANGER_GITLAB_API_TOKEN ] && [ "${PIPELINE_TYPE}" = "FORK_MR_PIPELINE" ]; then
+        echo "Danger token not configured. As this is from a fork, failing danger gracefully."
+        exit 202
+      fi
     - danger --fail-on-errors=true --verbose --danger_id=${danger_id}
+  allow_failure:
+    exit_codes: 202
   rules:
     - if: '$PIPELINE_TYPE =~ /MR_PIPELINE$/'
     - if: '$PIPELINE_TYPE == "DOCS_PIPELINE"'
